FROM node:18

COPY . /app

WORKDIR /app/bundle-generator
RUN yarn
RUN yarn build

WORKDIR /app/quiz-app
RUN yarn
RUN yarn build

RUN mkdir -p /app/dist/bundle-generator
RUN cp -r /app/bundle-generator/dist /app/dist/bundle-generator
RUN cp -r /app/quiz-app/dist /app/dist
